# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a603628c31a9a54199671521ca22c387"
name = "gsan-customer-portal"
handle = "gsan-customer-portal"
application_url = "https://16b9-142-231-7-19.ngrok-free.app/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "gsan-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_customers,read_orders,read_users"

[auth]
redirect_urls = [ 
  "https://16b9-142-231-7-19.ngrok-free.app/auth/callback",
  "https://16b9-142-231-7-19.ngrok-free.app/auth/shopify/callback",
  "https://16b9-142-231-7-19.ngrok-free.app/api/auth/callback" 
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
