# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a603628c31a9a54199671521ca22c387"
name = "gsan-customer-portal"
handle = "gsan-customer-portal"
application_url = "https://0b05-2604-3d08-4e82-a500-b5fc-227c-c477-5d58.ngrok-free.app/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "gsan-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customersunauthenticated_read_customers,unauthenticated_write_customers,read_online_store_navigation,read_orders,customer_read_customers"

[auth]
redirect_urls = [
  "https://0b05-2604-3d08-4e82-a500-b5fc-227c-c477-5d58.ngrok-free.app/auth/callback",
  "https://0b05-2604-3d08-4e82-a500-b5fc-227c-c477-5d58.ngrok-free.app/auth/shopify/callback",
  "https://0b05-2604-3d08-4e82-a500-b5fc-227c-c477-5d58.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://2826-2604-3d08-4e82-a500-b5fc-227c-c477-5d58.ngrok-free.app/webhooks/app/uninstalled"

[pos]
embedded = false
