# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d7984080909f698690013bb4a01a4a27"
name = "GSAN/Switch Customer Portal"
handle = "gsan-customer-portal-2"
application_url = "https://rhythm-sara-reviewed-weblog.trycloudflare.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gsan-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,unauthenticated_read_customers,unauthenticated_write_customers,read_online_store_navigation,read_orders,customer_read_customers"

[auth]
redirect_urls = [
  "https://rhythm-sara-reviewed-weblog.trycloudflare.com/auth/callback",
  "https://rhythm-sara-reviewed-weblog.trycloudflare.com/auth/shopify/callback",
  "https://rhythm-sara-reviewed-weblog.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://565f-2604-3d08-4e82-a500-4cc3-afca-b09c-e2be.ngrok-free.app/webhooks/app/uninstalled"

[pos]
embedded = false
